namespace AssetGroup
{
    /// <summary>
    /// An enumeration containing each kind of piece
    /// </summary>
    public enum Piece
    {
        None = 0,
        Pawn,
        Rook,
        Knight,
        Bishop,
        Queen,
        King,
        Private,
        Captain,
        Sergeant,
        Lieutenant,
        Colonel,
        General,
        Ferz,
        Wazir,
        Dabbaba,
        Taliah,
        Camel,
        Elephant,
        Giraffe,
        Swordsman,
        Fuhyo,
        Tokin,
        Hisha,
        Ryuo,
        Kakugyo,
        Ryuma,
        Keima,
        Narikei,
        Osho,
        Kyosha,
        Narikyo,
        Ginsho,
        Narigin,
        Kinsho,
        Zu,
        Ju,
        Ma,
        Xiang,
        Jiang,
        Shi,
        Pao,
    }
}
