namespace AssetGroup
{
    /// <summary>
    /// An enumeration containing each kind of tile
    /// </summary>
    public enum Tile
    {
        None = 0,
        WhiteSpace,
        BlackSpace,
        TrueWhiteSpace,
        TrueBlackSpace,
        BorderT,
        BorderPT,
        BorderB,
        BorderPB,
        BorderR,
        BorderL,
        BorderTR,
        BorderTL,
        BorderBR,
        BorderBL,
        BorderTRTL,
        BorderTRBR,
        BorderTRBL,
        BorderTLBR,
        BorderTLBL,
        BorderBRBL,
        BorderTRTLBR,
        BorderTRTLBL,
        BorderTRBRBL,
        BorderTLBRBL,
        BorderTRTLBRBL,
        InsideBorderTR,
        InsideBorderTL,
        InsideBorderTRL,
        InsideBorderPTR,
        InsideBorderPTL,
        InsideBorderPTRL,
        InsideBorderBR,
        InsideBorderBL,
        InsideBorderBRL,
        InsideBorderPBR,
        InsideBorderPBL,
        InsideBorderPBRL,
        InsideBorderTB,
        InsideBorderTBR,
        InsideBorderTBL,
        InsideBorderTBRL,
        InsideBorderPTB,
        InsideBorderPTBR,
        InsideBorderPTBL,
        InsideBorderPTBRL,
        InsideBorderTPB,
        InsideBorderTPBR,
        InsideBorderTPBL,
        InsideBorderTPBRL,
        InsideBorderPTPB,
        InsideBorderPTPBR,
        InsideBorderPTPBL,
        InsideBorderPTPBRL,
        InsideBorderRL,
    }
}
